name: Super-Linter

on: push

jobs:
  super-lin:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRNANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
